//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public KhuyenMai()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int KhuyenMaiID { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string Mota { get; set; }
        public double GiamGia { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
