//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.SanPhamHinhs = new HashSet<SanPhamHinh>();
            this.SanPhamSizes = new HashSet<SanPhamSize>();
        }
    
        public int SanPhamID { get; set; }
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public Nullable<byte> TrangThai { get; set; }
        public string Mota { get; set; }
        public int LoaiID { get; set; }
        public string NhaSanXuat { get; set; }
        public bool Deleted { get; set; }
        public int KhuyenMaiID { get; set; }
        public string BiDanh { get; set; }
        public Nullable<int> SoLanXem { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual ICollection<SanPhamHinh> SanPhamHinhs { get; set; }
        public virtual ICollection<SanPhamSize> SanPhamSizes { get; set; }
    }
}
