//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamSize
    {
        public SanPhamSize()
        {
            this.DonHangChiTiets = new HashSet<DonHangChiTiet>();
        }
    
        public int SanPhamSizeID { get; set; }
        public int SanPhamID { get; set; }
        public int SizeID { get; set; }
    
        public virtual ICollection<DonHangChiTiet> DonHangChiTiets { get; set; }
        public virtual SanPham SanPham { get; set; }
        public virtual Size Size { get; set; }
    }
}
