//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.SanPhamSizes = new HashSet<SanPhamSize>();
        }
    
        public int SizeID { get; set; }
        public string MaSize { get; set; }
        public string TenSize { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<SanPhamSize> SanPhamSizes { get; set; }
    }
}
